### ISSUE TITLE
Bug drawer

### ISSUE THREAD

**Issue by ghost** [Pehesi97/tournamanager#1]
O drawer não está fixado no topo da pagina e está dando este espaço branco, e também quando se abre o menu ele empurra os tabs fazendo com que o sublinhado saia fora do lugar.

![image](https://user-images.githubusercontent.com/35844466/40917522-ff753d04-67d9-11e8-8a23-bd1ff8e505fa.png)
![image](https://user-images.githubusercontent.com/35844466/40917560-16ae58de-67da-11e8-9667-386b26c3a81c.png)
![image](https://user-images.githubusercontent.com/35844466/40917583-2c305a5e-67da-11e8-9c15-602c9cfbd919.png)

**Comment by Pehesi97** [comment]
wtf.

**Comment by WiseWillian** [comment]
resolvível.. assim que tiver tempo resolvo isso

**Comment by Pehesi97** [comment]
fechou por que?
